#!/usr/bin/env python3
"""Marketplace similarity matrix for Section 4.2 (Cross-marketplace overlap).

Computes the Section 4.2 definition, J(A,B) = |C_A n C_B| / |C_A u C_B|, where C_X is
the set of cluster ids containing at least one file from marketplace X, and writes the
supplementary matrix the section refers to.

Input: `scan_20260314_threshold90_skillonly.json`, beside this script. The result is
therefore fixed to the 2026-03-14 corpus and does not depend on a live rescan. No
corpus access, no network, nothing randomised.

`marketplace_index` holds only the marketplaces with at least one clustered file, so
its size is not the corpus repository count. The run reconciles it against
`file_index`, names the omitted repositories in the output header, and exits non-zero
if a marketplace with clustered files is missing from the index.

Output: `paper/supplementary/marketplace-similarity-matrix.md`, overwritten each run.

Run:
  python paper/sources/scans/marketplace_matrix.py
"""
import json, sys, itertools
from pathlib import Path

SCAN = Path(__file__).with_name("scan_20260314_threshold90_skillonly.json")
OUT = Path(__file__).resolve().parents[2] / "supplementary" / "marketplace-similarity-matrix.md"

def main() -> int:
    data = json.loads(SCAN.read_text())
    index = data["marketplace_index"]
    if not isinstance(index, dict) or not index:
        print(f"marketplace_index missing or empty in {SCAN}", file=sys.stderr)
        return 1
    # DESIGN RATIONALE: `marketplace_index` holds only the marketplaces with at
    # least one clustered file, so its size is not the corpus repository count.
    # Reconciling it against `file_index` here is what stops the header line
    # "Marketplaces: 25" from being read as the corpus size (32 repositories).
    corpus = {}
    for e in data["file_index"]:
        m = corpus.setdefault(e["marketplace"], {"files": 0, "clustered": 0})
        m["files"] += 1
        m["clustered"] += 1 if e.get("in_cluster") else 0
    omitted = sorted(set(corpus) - set(index))
    with_clustered = {m for m, c in corpus.items() if c["clustered"]}
    unexpected = sorted(with_clustered - set(index))
    if unexpected:
        print("marketplaces with clustered files are missing from marketplace_index: "
              + ", ".join(unexpected), file=sys.stderr)
        return 1
    omitted_files = sum(corpus[m]["files"] for m in omitted)
    omitted_clustered = sum(corpus[m]["clustered"] for m in omitted)

    sets = {m: set(cids) for m, cids in index.items()}
    names = sorted(sets)
    pairs = []
    for a, b in itertools.combinations(names, 2):
        union = sets[a] | sets[b]
        j = len(sets[a] & sets[b]) / len(union) if union else 0.0
        pairs.append((j, a, b, len(sets[a] & sets[b]), len(union)))
    pairs.sort(reverse=True)
    lines = ["# Marketplace similarity matrix (90% threshold, SKILL.md only, 2026-03-14 scan)", "",
             "Definition (paper Section 4.2): Jaccard similarity of cluster-membership sets,",
             "|C_A ∩ C_B| / |C_A ∪ C_B|, where C_X is the set of cluster ids containing at",
             f"least one file from marketplace X. Source: `{SCAN.name}`, generated by `{Path(__file__).name}`.", "",
             f"Marketplaces: {len(names)} of the {len(corpus)} corpus repositories, namely those "
             f"with at least one clustered file. The other {len(omitted)} are omitted because they "
             f"contribute no cluster and so have no membership set to compare "
             f"({omitted_files} files, {omitted_clustered} clustered): "
             + ", ".join(f"`{m}`" for m in omitted) + ".", "",
             f"Pairs with non-zero overlap: {sum(1 for p in pairs if p[0] > 0)} of the "
             f"{len(names) * (len(names) - 1) // 2} possible pairs "
             f"({100.0 * sum(1 for p in pairs if p[0] > 0) / (len(names) * (len(names) - 1) // 2):.1f}%).", "",
             "## Pairs with non-zero overlap, descending", "",
             "| Marketplace A | Marketplace B | Shared clusters | Union | Jaccard |", "|---|---|---:|---:|---:|"]
    for j, a, b, inter, union in pairs:
        if j > 0:
            lines.append(f"| {a} | {b} | {inter} | {union} | {j:.3f} |")
    lines += ["", "## Full matrix (Jaccard, rows and columns in the same order)", "",
              "| | " + " | ".join(names) + " |", "|---|" + "---|" * len(names)]
    for a in names:
        row = []
        for b in names:
            union = sets[a] | sets[b]
            row.append(f"{(len(sets[a] & sets[b]) / len(union) if union else 0.0):.3f}")
        lines.append(f"| {a} | " + " | ".join(row) + " |")
    lines += ["", "## Provenance", "",
              "This file was generated from the archived 2026-03-14 scan at "
              "threshold 0.9 over SKILL.md files only, the method stated in the paper. It "
              "supersedes an earlier figure (53.8% between every-marketplace "
              "and side-quest-marketplace), which came from an earlier scan of 2026-03-13 at the "
              "tool's default 0.7 threshold over all Markdown files of a 17-marketplace corpus. "
              + (f"Under the paper's stated method that pair is not computable rather than measured "
                 f"at zero: `side-quest-marketplace` contributes "
                 f"{corpus.get('side-quest-marketplace', {}).get('clustered', 0)} clustered files "
                 f"out of {corpus.get('side-quest-marketplace', {}).get('files', 0)}, so its "
                 f"membership set is empty and the Jaccard ratio has no denominator."
                 if 'side-quest-marketplace' in omitted else
                 "Under the paper's stated method that pair shares no cluster.")
              + " The two pairs at 1.000 are mirror pairs: one upstream repository cloned into the "
                "corpus under two directory names, as recorded in the Notes of "
                "`paper/supplementary/repository-commits.md`."]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    top3 = pairs[:3]
    print(f"wrote {OUT}")
    for rank, (j, a, b, inter, union) in enumerate(top3, start=1):
        print(f"top {rank}: {a} / {b} = {j:.3f} ({inter}/{union})")
    return 0

if __name__ == "__main__":
    sys.exit(main())
