#!/usr/bin/env python3
"""Marketplace similarity matrix for Section 4.2 (Marketplace Similarity Matrix).

The paper defines the score in Section 4.2: "Plugin Librarian computes a
marketplace-level similarity score as the Jaccard similarity of cluster membership
sets: |C_A ∩ C_B| / |C_A ∪ C_B|, where C_X is the set of cluster IDs containing files
from marketplace X." The section ends with "The full matrix is given with the artifact
(Appendix C)." This script computes that score for every pair of marketplaces and
writes that matrix.

Input: `paper/sources/scans/scan_20260314_threshold90_skillonly.json`, the archived
scan report of 2026-03-14 at threshold 0.9 over SKILL.md files only (the method of
Section 3.3), located beside this script. The result is fixed to that scan. Nothing
here reads the corpus, touches the network, or is randomized.

`marketplace_index` in the report holds only the marketplaces with at least one
clustered file, so its size is not the corpus repository count. The script reconciles
it against `file_index`, names the omitted repositories in the output header, and
exits non-zero if a marketplace with clustered files is missing from the index.

Output: `paper/supplementary/marketplace-similarity-matrix.md`, overwritten each run.

Run from the repository root:
  python paper/sources/scans/marketplace_matrix.py
LIBRARIAN_CORPUS is not read; the archived scan report is the only input.
"""
import json, sys, itertools
from pathlib import Path

SCAN = Path(__file__).with_name("scan_20260314_threshold90_skillonly.json")
OUT = Path(__file__).resolve().parents[2] / "supplementary" / "marketplace-similarity-matrix.md"

# DESIGN RATIONALE: this file anchors to the paper by section, table and figure
# number and never quotes its text, so that an edit to a paper sentence cannot
# strand a quotation here. The section below is restated in this file's own
# words. The rule holds for every script and results file in the bundle: an
# anchor survives a rewording of the sentence it points at, a quotation does not.

def main() -> int:
    data = json.loads(SCAN.read_text())
    index = data["marketplace_index"]
    if not isinstance(index, dict) or not index:
        print(f"marketplace_index missing or empty in {SCAN}", file=sys.stderr)
        return 1
    # DESIGN RATIONALE: `marketplace_index` holds only the marketplaces with at
    # least one clustered file, so its size is not the corpus repository count.
    # Reconciling it against `file_index` here is what stops the header's
    # marketplace count from being read as the corpus size, and it lets the
    # header name the repositories that have no membership set to compare.
    corpus = {}
    for e in data["file_index"]:
        m = corpus.setdefault(e["marketplace"], {"files": 0, "clustered": 0})
        m["files"] += 1
        m["clustered"] += 1 if e.get("in_cluster") else 0
    omitted = sorted(set(corpus) - set(index))
    with_clustered = {m for m, c in corpus.items() if c["clustered"]}
    unexpected = sorted(with_clustered - set(index))
    if unexpected:
        print("marketplaces with clustered files are missing from marketplace_index: "
              + ", ".join(unexpected), file=sys.stderr)
        return 1
    omitted_files = sum(corpus[m]["files"] for m in omitted)
    omitted_clustered = sum(corpus[m]["clustered"] for m in omitted)

    sets = {m: set(cids) for m, cids in index.items()}
    names = sorted(sets)
    pairs = []
    for a, b in itertools.combinations(names, 2):
        union = sets[a] | sets[b]
        j = len(sets[a] & sets[b]) / len(union) if union else 0.0
        pairs.append((j, a, b, len(sets[a] & sets[b]), len(union)))
    pairs.sort(reverse=True)
    lines = ["# Marketplace similarity matrix (90% threshold, SKILL.md only, 2026-03-14 scan)", "",
             "This file reports the pairwise Jaccard similarity of cluster membership sets for every "
             "marketplace in the corpus that contributes at least one cluster. It is the full matrix "
             "that Section 4.2 (Marketplace Similarity Matrix) describes and that Appendix C "
             "(Reproduction) lists among the released files. Section 4.2 defines the score as the "
             "Jaccard similarity of cluster membership sets, |C_A \u2229 C_B| / |C_A \u222a C_B|, where "
             "C_X is the set of cluster IDs holding files from marketplace X. The first three rows of "
             "the first table below are the pairs that section names: the two mirror pairs at 1.000 "
             "and the highest non-mirror pair.", "",
             f"Input: `paper/sources/scans/{SCAN.name}`, the archived scan report at threshold 0.9 over "
             f"SKILL.md files only. Generated by `paper/sources/scans/{Path(__file__).name}`; run "
             f"`python paper/sources/scans/{Path(__file__).name}` from the repository root to "
             "regenerate it. No environment variable is required.", "",
             f"Marketplaces: {len(names)} of the {len(corpus)} corpus repositories, namely those "
             f"with at least one clustered file. The other {len(omitted)} are omitted because they "
             f"contribute no cluster and so have no membership set to compare "
             f"({omitted_files} files, {omitted_clustered} clustered): "
             + ", ".join(f"`{m}`" for m in omitted) + ".", "",
             f"Pairs with non-zero overlap: {sum(1 for p in pairs if p[0] > 0)} of the "
             f"{len(names) * (len(names) - 1) // 2} possible pairs "
             f"({100.0 * sum(1 for p in pairs if p[0] > 0) / (len(names) * (len(names) - 1) // 2):.1f}%).", "",
             "## Pairs with non-zero overlap, descending", "",
             "| Marketplace A | Marketplace B | Shared clusters | Union | Jaccard |", "|---|---|---:|---:|---:|"]
    for j, a, b, inter, union in pairs:
        if j > 0:
            lines.append(f"| {a} | {b} | {inter} | {union} | {j:.3f} |")
    lines += ["", "## Full matrix (Jaccard, rows and columns in the same order)", "",
              "| | " + " | ".join(names) + " |", "|---|" + "---|" * len(names)]
    for a in names:
        row = []
        for b in names:
            union = sets[a] | sets[b]
            row.append(f"{(len(sets[a] & sets[b]) / len(union) if union else 0.0):.3f}")
        lines.append(f"| {a} | " + " | ".join(row) + " |")
    lines += ["", "## Provenance", "",
              "This file was generated from the archived 2026-03-14 scan at threshold 0.9 over "
              "SKILL.md files only, the method stated in Section 3.3 of the paper. Pairs that "
              "involve an omitted marketplace appear in neither table: an omitted marketplace has "
              "an empty membership set, so its Jaccard against any listed marketplace is 0.000 and "
              "against another omitted marketplace has an empty union and no value. "
              + (f"`side-quest-marketplace` is one such case; it contributes "
                 f"{corpus.get('side-quest-marketplace', {}).get('clustered', 0)} clustered files "
                 f"out of {corpus.get('side-quest-marketplace', {}).get('files', 0)}. "
                 if 'side-quest-marketplace' in omitted else "")
              + "The two pairs at 1.000 are mirror pairs: one upstream repository cloned into the "
                "corpus under two directory names, as recorded in the Notes of "
                "`paper/supplementary/repository-commits.md`."]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    top3 = pairs[:3]
    print(f"wrote {OUT}")
    for rank, (j, a, b, inter, union) in enumerate(top3, start=1):
        print(f"top {rank}: {a} / {b} = {j:.3f} ({inter}/{union})")
    return 0

if __name__ == "__main__":
    sys.exit(main())
