#!/usr/bin/env python3
"""Distinct clustered files and cluster memberships per Jaccard threshold, for Table 2.

Clusters overlap, so the sum of cluster sizes (memberships) exceeds the number of
distinct files that belong to at least one cluster. Table 2 of the paper (Section 4.1,
Ecosystem Characterization) reports distinct files in its *Files* column, and the
opening figures of Section 4.1 give both counts at the 90% threshold: the cluster
count, the membership count, the distinct clustered file count and its share of the
file index, with memberships exceeding files because clusters may overlap. Table 5
(shingle size ablation, Section 5.2) reports memberships. This script reads each archived scan and prints, per threshold:
cluster count, memberships, distinct clustered files, and each of the last two as a
share of the file index.

Inputs: the six archived scans beside this script,
`scan_20260314_threshold{70,75,80,85,90,95}_skillonly.json`. No corpus access, no
network, no environment variables, nothing randomized.

Output: `table2-distinct-files-20260907.md` beside this script.

Options: --check verifies that file instead of rewriting it, and reports a unified
diff on a mismatch.

Self-test (before any archived scan is read): a two-cluster toy scan with one overlapping file
must give memberships 5 and distinct 4, so the two counts cannot be confused; a second,
deliberately mismatched toy scan exercises the consistency check that guards against
`in_cluster` flags disagreeing with cluster locations.

Run:
  python paper/sources/scans/table2_distinct_files.py [--check]
"""
import argparse
import difflib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
THRESHOLDS = (70, 75, 80, 85, 90, 95)
OUT = HERE / "table2-distinct-files-20260907.md"


def flagged_set(scan):
    return {e["file_index"] for e in scan["file_index"] if e.get("in_cluster")}


def distinct_set(scan):
    return {loc["file_index"] for c in scan["clusters"] for loc in c["locations"]}


def check_consistency(scan):
    """Symmetric difference between in_cluster-flagged file_index values and the
    file_index values that actually appear in cluster locations. Empty means consistent."""
    return flagged_set(scan) ^ distinct_set(scan)


def counts(scan):
    clusters = scan["clusters"]
    n = len(scan["file_index"])
    memberships = sum(len(c["locations"]) for c in clusters)
    distinct = distinct_set(scan)
    flagged = flagged_set(scan)
    return len(clusters), memberships, len(distinct), len(flagged), n


def self_test():
    toy = {"file_index": [{"file_index": i, "in_cluster": i < 4} for i in range(6)],
           "clusters": [{"locations": [{"file_index": 0}, {"file_index": 1}, {"file_index": 2}]},
                        {"locations": [{"file_index": 2}, {"file_index": 3}]}]}
    got = counts(toy)
    want = (2, 5, 4, 4, 6)
    if got != want:
        print(f"self-test FAILED: got {got}, want {want}", file=sys.stderr)
        sys.exit(1)
    mismatch = check_consistency(toy)
    if mismatch:
        print(f"self-test FAILED: consistent toy scan flagged a mismatch {mismatch}", file=sys.stderr)
        sys.exit(1)

    bad = {"file_index": [{"file_index": i, "in_cluster": i < 3} for i in range(6)],
           "clusters": [{"locations": [{"file_index": 0}, {"file_index": 1}, {"file_index": 2}]},
                        {"locations": [{"file_index": 2}, {"file_index": 3}]}]}
    bad_mismatch = check_consistency(bad)
    if bad_mismatch != {3}:
        print(f"self-test FAILED: inconsistent toy scan gave {bad_mismatch}, want {{3}}", file=sys.stderr)
        sys.exit(1)
    print("self-test PASS: 2 clusters, 5 memberships, 4 distinct, 6 indexed; "
          "inconsistency check flags {3} on a deliberately mismatched toy scan")


def build_report(rows):
    lines = ["# Table 2: distinct clustered files and memberships per threshold",
             "",
             "Generated by `paper/sources/scans/table2_distinct_files.py` on 2026-09-07 from the six archived "
             "scans `scan_20260314_threshold{70,75,80,85,90,95}_skillonly.json`. This file reports, for each "
             "Jaccard threshold in the sweep, the cluster count, the number of cluster memberships, and the "
             "number of distinct clustered files, with the last two also as shares of the file index.",
             "",
             "It supports Table 2 (Section 4.1, Ecosystem Characterization), whose *Files* column is "
             "the *Distinct* column here, and the opening figures of Section 4.1 for the 90% threshold: "
             "the cluster count, the membership count, the distinct clustered file count and its share of "
             "the file index, with memberships exceeding files because clusters may overlap. The "
             "*Memberships* column is the count Table 5 (shingle size ablation, Section 5.2) reports in "
             "its 3-gram row.",
             "",
             "*Memberships* is the sum of cluster sizes. *Distinct* is the number of distinct `file_index` "
             "values across all clusters; the script checks that it equals the count of `in_cluster` flags "
             "in each scan's `file_index` and stops on any disagreement. Percentages are over the file index.",
             "",
             "| Threshold | Clusters | Memberships | Memberships % | Distinct | Distinct % |",
             "|---:|---:|---:|---:|---:|---:|"]
    for t, ncl, mem, dist, n in rows:
        lines.append(f"| {t}% | {ncl:,} | {mem:,} | {100*mem/n:.1f}% | {dist:,} | {100*dist/n:.1f}% |")
    lines.append("")
    lines.append(f"File index size is {rows[0][4]:,} at every threshold (same input list, "
                 "the scan's `file_index`).")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Recompute Table 2 as distinct clustered files.")
    parser.add_argument("--check", action="store_true",
                         help="verify the existing results file instead of rewriting it")
    args = parser.parse_args()
    self_test()

    rows = []
    for t in THRESHOLDS:
        path = HERE / f"scan_20260314_threshold{t}_skillonly.json"
        scan = json.loads(path.read_text(encoding="utf-8"))
        ncl, mem, dist, _flagged, n = counts(scan)
        mismatch = check_consistency(scan)
        if mismatch:
            print(f"{t}%: in_cluster flags and cluster locations disagree on {len(mismatch)} file(s)",
                  file=sys.stderr)
            sys.exit(1)
        rows.append((t, ncl, mem, dist, n))
        print(f"{t}%  clusters {ncl:,}  memberships {mem:,} ({100*mem/n:.1f}%)  "
              f"distinct {dist:,} ({100*dist/n:.1f}%)  of {n:,}")

    report = build_report(rows)

    if args.check:
        existing = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if report == existing:
            print(f"{OUT.name} matches recomputation")
            sys.exit(0)
        diff = difflib.unified_diff(existing.splitlines(keepends=True), report.splitlines(keepends=True),
                                     fromfile=str(OUT.name), tofile="recomputed")
        sys.stdout.writelines(diff)
        sys.exit(1)

    OUT.write_text(report, encoding="utf-8")
    print(f"wrote {OUT.name}")


if __name__ == "__main__":
    main()
